---
language: objective-c
sudo: required

before_install:
  - brew update

install:
  - brew install ansible --HEAD
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -c local -vvv -b -t configure
  # - [ $(defaults read com.apple.battery ShowPercent) == "YES" ]
  - "[ $(defaults read /Library/Preferences/.GlobalPreferences
    AppleInterfaceTheme) == 'Dark' ]"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
