---

#####=== install ===#####

# - name: update | system
  # command: 'softwareupdate --install --all'
  # when: ansible_distribution == 'MacOSX'
  # tags:
    # - bootstrap
    # - install
    # - update

#####=== configure ===#####

# TODO: use the osx_defaults module instead of osx.sh
- name: configure | system
  command: osx.sh
  args:
    chdir: files
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - configure
