---

# - name: setup
  # include_vars: "{{ ansible_user_shell | basename }}.yml"

#####=== install ===#####

- name: OS X | update
  command: 'softwareupdate --install --all'
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - update

#####=== configure ===#####

# TODO: transition to using the osx_defaults module instead of osx.sh
shell: osx.sh
when: ansible_distribution == 'MacOSX'
tags: bootstrap
