---

#####=== install ===#####

- name: update | system
  command: 'softwareupdate --install --all'
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - bootstrap_osx
    - install
    - install_osx
    - update
    - update_osx

#####=== configure ===#####

# TODO: use the osx_defaults module instead of osx.sh
- name: configure | system
  script: osx.sh {{ ansible_hostname }}
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - bootstrap_osx
    - configure
    - configure_osx
