---

#####=== install ===#####

# - name: update | system
  # command: 'softwareupdate --install --all'
  # when: ansible_distribution == 'MacOSX'
  # tags:
    # - bootstrap
    # - bootstrap_macos
    # - install
    # - install_macos
    # - update
    # - update_macos

#####=== configure ===#####

- name: configure | system
  osx_defaults: 
    domain: "{{ item.0.domain }}"
    key: "{{ item.1.name }}"
    type: "{{ item.1.type }}"
    value: "{{ (macos_use_default_values == true) | ternary(item.1.default_value, item.1.value) }}"
  with_subelements: 
    - "{{ macos_settings }}"
    - keys
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - bootstrap_macos
    - configure
    - configure_macos
