---

#####=== install ===#####

- name: update | system
  command: 'softwareupdate --install --all'
  when: (ansible_distribution == 'MacOSX') and (install_state == 'latest')
  tags:
    - bootstrap
    - install
    - update

#####=== configure ===#####

# TODO: use the osx_defaults module instead of osx.sh
- name: configure | system
  shell: ./osx.sh
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - configure
